In [1]:
import numpy as np

In [2]:
 print(np.__version__)
 np.show_config()

1.15.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [4]:
Z = np.zeros(10)

In [5]:
 Z = np.zeros((10,10))
 print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [11]:
np.info(np.add)

AttributeError: module 'numpy' has no attribute 'reverse'

In [9]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [13]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
nz = np.nonzero([1,2,0,0,4,0]) #返回非零元素位置
print(nz)

(array([0, 1, 4], dtype=int64),)


In [15]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.58331491 0.20031064 0.30702082 0.7876521  0.02356625 0.63045194
   0.62091113 0.04727419]
  [0.34887994 0.27634926 0.7470174  0.35141945 0.24838023 0.20365441
   0.57356457 0.77924874]
  [0.15969262 0.82767669 0.82734674 0.12999651 0.57163078 0.02355913
   0.12996836 0.20487567]
  [0.24769401 0.99366997 0.91650729 0.39043187 0.21354152 0.24166064
   0.48432812 0.33318158]
  [0.25979242 0.10034723 0.55032469 0.53313796 0.32620618 0.38145809
   0.44583132 0.21994098]
  [0.06715546 0.28686282 0.71002308 0.65868645 0.87150797 0.12009804
   0.15898292 0.69535507]
  [0.89402139 0.38574308 0.227391   0.81241135 0.3007958  0.09194215
   0.99178099 0.30620587]]

 [[0.44847794 0.03107561 0.5578387  0.03122116 0.51048403 0.19429103
   0.00939205 0.83427219]
  [0.01112901 0.85320716 0.75861428 0.90621867 0.66917378 0.16537456
   0.86274679 0.71769704]
  [0.97490634 0.09403153 0.76851654 0.34226392 0.17031153 0.53579555
   0.79183188 0.72829498]
  [0.67864007 0.30320117 0.47533276 0.13888696 0

In [24]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.002019140343453296 0.9982629951218153


In [26]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4831080266036293
[0.25146865 0.34958557 0.91315255 0.28453394 0.5401121  0.37681823
 0.25945372 0.88606753 0.92398012 0.24681483 0.53207147 0.67068547
 0.52445487 0.42805842 0.80410691 0.8324976  0.3710678  0.02779328
 0.46266101 0.02987507 0.76920314 0.45039021 0.91515912 0.74672485
 0.33633231 0.51676315 0.0654799  0.25432867 0.67055327 0.05304704]


In [27]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
 Z = np.ones((5,5))
 Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)  #填充值为0的边界
print(Z)   

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [40]:
a=0 * np.nan
b=np.nan == np.nan
c=np.inf > np.nan
d=np.nan - np.nan
e=0.3 == 3 * 0.1
print(a,b,c,d,e)

nan False False nan False


In [41]:
Z = np.diag(1+np.arange(4),k=-1) #获取对角线元素，k调节位置
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [44]:
 Z = np.zeros((8,8),dtype=int)
 Z[1::2,::2] = 1
 Z[::2,1::2] = 1
 print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [45]:
print(np.unravel_index(100,(6,7,8)))  #第100个元素的位置

(1, 5, 4)


In [50]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [51]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)


[[0.52041261 0.76477851 0.43044025 0.5283062  0.79838392]
 [0.26694782 0.14533056 0.         0.19536839 0.33394338]
 [0.825288   0.70033392 0.79475974 0.14564586 0.21144019]
 [0.35949706 0.09554551 0.11348423 0.68047383 0.50516094]
 [0.07185487 0.17102349 1.         0.72863781 0.68069686]]


In [52]:
color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)]) 
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [56]:
 Z = np.dot(np.ones((5,3)), np.ones((3,2)))
 print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [58]:
Z = np.arange(11)
Z[(3 <= Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [76]:
print(sum(range(5),-1))

10


In [78]:
from numpy import *   #引入numpy但是不需要加前缀
print(sum(range(5),-1))

10


In [87]:
Z = np.arange(5)
Z ** Z  # legal
print(2 << Z >> 2) #不合法
Z <- Z  #合法
1j*Z   # legal
Z/1/1   # legal
Z<Z>Z    # false
print(1j)

[0 1 2 4 8]
1j


In [88]:
print(np.array(0) / np.array(0))

nan


e:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [89]:
print(np.array(0) // np.array(0))

0


e:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [90]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [95]:
Z = np.random.uniform(-10,+10,10)  #最后一个为样本数目
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))
print(np.abs(Z))

[ 9.76359799 -0.92049036  5.70714996 -5.39432557  7.92508371  1.90943681
 -4.3538045   8.21462306  3.48521492 -9.25887587]
[ 10.  -1.   6.  -6.   8.   2.  -5.   9.   4. -10.]
[9.76359799 0.92049036 5.70714996 5.39432557 7.92508371 1.90943681
 4.3538045  8.21462306 3.48521492 9.25887587]


In [98]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
print(Z1)

[3]
[5 3 0 0 5 9 1 1 1 1]


In [100]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [101]:
np.sqrt(-1) == np.emath.sqrt(-1)  #False

e:\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [102]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-05
Today is 2019-08-06
Tomorrow is 2019-08-07


In [103]:
 Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
 print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [109]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [112]:
Z = np.random.uniform(0,10,10)  #不同方法取整数部分
print (Z-Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[8. 9. 5. 0. 2. 1. 0. 2. 8. 5.]


In [113]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [114]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [117]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


In [118]:
Z = np.random.random(10)
Z.sort()  #排序
print (Z)

[0.02835499 0.06924646 0.12978636 0.17735785 0.24753525 0.50619718
 0.78967206 0.85457597 0.91759878 0.91791437]


In [119]:
Z = np.arange(10)
np.add.reduce(Z)  #小组数快速求和

45

In [122]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)
# 方法2 Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[0 1 1 0 1]


In [123]:
Z = np.zeros(10)
Z.flags.writeable = False  #让数组变成只读
Z[0] = 1

ValueError: assignment destination is read-only

In [124]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)   #转为极坐标
T = np.arctan2(Y,X)
print (R)
print (T)

[0.98016505 0.96273846 1.00570683 0.78172213 0.86809731 0.66082375
 0.48081537 0.59099462 0.70064538 0.32700299]
[0.92424398 1.46836835 1.36715661 0.93037098 0.34514835 0.16914551
 1.09881382 1.38358592 1.08014974 1.08613058]


In [126]:
Z = np.random.random(10)
Z[Z.argmax()] = 1 将最大值替换为1
print (Z)

[0.03055872 0.4124959  0.57803662 0.7335303  1.         0.93480912
 0.5999743  0.80431591 0.35517825 0.33003609]


In [127]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),   #创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [129]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y) #给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
print(C)
#print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


In [130]:
# 打印每个numpy标量类型的最小值和最大值
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [131]:
#  如何打印一个数组中的所有数值
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#  给定标量时，如何找到数组中最接近标量的值
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin() 
print (Z[index])